@host = http://localhost:5178

### Health check
GET {{host}}/
Accept: application/json

### List all products
GET {{host}}/api/products
Accept: application/json

### Get a product by barcode
GET {{host}}/api/products/5701234567890
Accept: application/json

### Add or update a product (upsert)
POST {{host}}/api/products
Content-Type: application/json

{
  "barcode": "5701234567890",
  "name": "Schar Gluten Free Bread",
  "ingredients": "Water, corn starch, sourdough, rice starch, soy flour, salt, yeast.",
  "glutenRating": "gluten_free"
}
